### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by H4ckBu7eer-EX** [Zakiaatot/TermDo_app#1]
我在做一个安卓渗透的APP 请问可以集成这个终端到我的APP吗 我采用andlua开发

**Comment by Zakiaatot** [comment]
你好，直接集成恐怕是不行的，但是后端功能部分你可以参考我的Termdo_core实现,封装一个java包然后用lua去调用，前端页面也需要自己去实现。

**Comment by H4ckBu7eer-EX** [comment]
> 你好，直接集成恐怕是不行的，但是后端功能部分你可以参考我的Termdo_core实现,封装一个java包然后用lua去调用，前端页面也需要自己去实现。

感谢
